<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Actions\GenerateInvoicePdf;
use App\Models\Invoice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

class InvoicePdfDownloadController extends Controller
{
    /**
     * Stream an invoice PDF via a single-use signed URL.
     *
     * The signature itself is the authorisation: it can only be generated by
     * a caller who already passed the invoices.download_pdf tool's policy
     * check, and it is bound to this specific invoice id. A second request
     * with the same signature is refused, so a link that leaks (chat log,
     * proxy, browser history) has a narrow window of use.
     */
    public function __invoke(Request $request, Invoice $invoice): StreamedResponse
    {
        abort_unless($request->hasValidSignature(), 403, 'This link is invalid or has expired.');

        $cacheKey = 'invoice-pdf-link-used:'.sha1((string) $request->fullUrl());

        abort_if(Cache::has($cacheKey), 403, 'This link has already been used.');

        Cache::put($cacheKey, true, now()->addMinutes(20));

        $path = app(GenerateInvoicePdf::class)($invoice);

        return Storage::disk('local')->download($path, "{$invoice->number}.pdf");
    }
}
